services:
  php:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.php
    image: php
    container_name: "php"
    restart: always
    ports:
     - "9000:9000"
    env_file: ".env"
    volumes:
     - ./src:/var/www/html
    depends_on:
      - mariadb
    networks:
     - app-network

  nginx:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.nginx
    image: nginx
    container_name: "nginx"
    restart: "always"
    ports:
      - "8443:443"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  maria-db:


